GET http://localhost:8880/ebook/list
Accept: application/json

###

GET http://localhost:8880/ebook/list?name=mysql
Accept: application/json

###

GET http://localhost:8880/ebook/list?page=3&size=2
Accept: application/json

###